#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

[ -f "$MBSYNCRC" ] && alias mbsync="mbsync -c $MBSYNCRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

se() {
	choice="$(find ~/.local/bin -mindepth 1 -printf '%P\n' | fzf)"
	[ -f "$HOME/.local/bin/$choice" ] && $EDITOR "$HOME/.local/bin/$choice"
	;}



ff265to264() {
	ffmpeg -i "$1" -c:v libx264 -crf 23 -c:a aac -strict experimental "$2"
}
ffcropaudio() {
	ffmpeg -i "$1" -ss "$2" -to "$3" -c copy "output_$1"
}
ffcropvideo_middle(){
	ffmpeg -i "$1" -ss "$2" -to "$3" -c:v copy -c:a copy "output_$1"
}
ffcropvideo_end(){
	ffmpeg -i "$1" -ss "$2" -c:v copy -c:a copy "output_$1"
}
#00:01:30





# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	cphdd="rsync -ah --info=progress2" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	rsync="rsync -vrPlu" \
	mkd="mkdir -pv" \
	ytq="yt-dlp --embed-metadata -i --write-sub" \
	ytt="yt --skip-download --write-thumbnail" \
	ytd="yt --skip-download --write-thumbnail --add-metadata" \
	ffmpeg="ffmpeg -hide_banner" \
	yta="yt -x -f bestaudio/best"



# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	z="zathura"

alias \
	lf="lfub" \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	weath="less -S ${XDG_CACHE_HOME:-$HOME/.cache}/weatherreport" \
